import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

await mkdir('test-results',{recursive:true});
const browser=await chromium.launch();
try {
 const context=await browser.newContext({viewport:{width:390,height:844},locale:'de-DE',permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.clock.install({time:new Date('2026-09-07T10:00:00Z')});
 await page.goto('http://127.0.0.1:3000/');
 assert.equal(await page.locator('.dish').count(),124);
 assert.equal(await page.locator('.dish:visible').count(),8);
 await page.locator('[data-menu-category="reis"]').click();
 await expect(page.locator('[data-menu-category="reis"]')).toHaveAttribute('aria-current','true');
 assert.equal(await page.locator('.dish:visible').count(),5);
 await page.locator('[data-menu-category="sushi-menues"]').click();
 assert.equal(await page.locator('.dish:visible').count(),8);
 assert.equal(await page.locator('[data-item="hana-330"] .dish-media img').count(),1);
 assert.equal(await page.locator('[data-item="hana-331"] .dish-media img').count(),0);
 await page.locator('.dish:visible .dish-media img').evaluateAll(images=>Promise.all(images.map(image=>image.decode())));
 assert.equal(await page.locator('.dish:visible .dish-media img').evaluateAll(images=>images.filter(image=>!image.complete||image.naturalWidth===0).length),0);
 await page.reload();
 await expect(page.locator('[data-menu-category="sushi-menues"]')).toHaveAttribute('aria-current','true');
 await page.locator('[data-menu-category="all"]').click();
 assert.equal(await page.locator('.dish:visible').count(),8);
 await page.locator('#dish-search').fill('28G');
 assert.equal(await page.locator('.dish:visible').count(),1);
 assert.equal(await page.locator('#variant-28').inputValue(),'hana-28g');
 await page.locator('[data-add="hana-28g"]').click();
 await expect(page.locator('[data-options^="hana-28a"] [data-dish-count]')).toHaveText('1 ×');
 await page.locator('#reset-menu').click();
 await page.locator('#dish-search').fill('Udon');
 await page.locator('[data-filter="vegetarian"]').click();
 assert.equal(await page.locator('#variant-28').inputValue(),'hana-28a');
 assert.equal(await page.locator('#variant-28 option:not([disabled])').count(),1);
 await page.locator('[data-filter="all"]').click();
 await page.locator('#variant-28').selectOption('hana-28b');
 await page.locator('[data-add="hana-28b"]').click();
 await page.locator('#dish-search').fill('xyz-absent');
 assert.equal(await page.locator('#no-results').isVisible(),true);
 await page.locator('#reset-menu').click();
 await page.locator('#dish-search').fill('Sake Nigiri');
 await page.locator('[data-add="hana-213"]').click();
 await page.setViewportSize({width:1440,height:1000});
 await expect(page.locator('[data-cart-summary]').first()).toContainText('36,00');
 await page.locator('.menu-total [data-open-cart]').click();
 await expect(page.locator('#cart-items')).toContainText('Garnelen');
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:390,height:844});
 await page.reload();
 await page.locator('.mobile-actions [data-open-cart]').click();
 assert.match(await page.locator('#cart-total').textContent(),/36,00/);
 await page.locator('[data-quantity="hana-213"][data-change="1"]').click();
 assert.match(await page.locator('#cart-total').textContent(),/41,00/);
 await page.locator('[data-quantity="hana-213"][data-change="-1"]').click();
 await page.locator('#checkout-button').click();
 const order=page.locator('#order-form');
 await order.locator('[name=name]').fill('Testgast Hana');
 await order.locator('[name=phone]').fill('abcdefghi');
 await order.locator('[name=date]').fill('2026-09-08');
 await order.locator('[name=time]').selectOption('12:30');
 await order.locator('[type=submit]').click();
 assert.match(await page.locator('#form-error').textContent(),/Telefonnummer/);
 await order.locator('[name=phone]').fill('+49 123456789');
 await order.locator('[name=notes]').fill('Testanfrage – nicht versenden. Ohne Koriander.');
 await order.locator('[type=submit]').click();
 const message=await page.locator('#order-message').textContent();
 for(const text of ['28G. Gebratener Udon (Garnelen)','28B. Gebratener Udon (Hühnerfleisch)','213. Sake Nigiri','36,00','Ohne Koriander'])assert.ok(message.includes(text),text);
 const orderHref=await page.locator('#send-order').getAttribute('href');
 assert.ok(orderHref.startsWith('https://wa.me/4915257186870?text='));
 assert.ok(decodeURIComponent(orderHref).includes(message));
 await page.locator('#copy-order').click();
 await expect(page.locator('#order-copy-status')).toContainText('kopiert');
 let axe=await new AxeBuilder({page}).analyze();assert.deepEqual(axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);
 await page.screenshot({path:'test-results/order-review-mobile.png'});
 await page.locator('#edit-order').click();
 await page.locator('[data-remove="hana-213"]').click();
 assert.match(await page.locator('#cart-total').textContent(),/31,00/);
 await page.locator('#checkout-button').click();
 assert.equal(await order.locator('[name=name]').inputValue(),'Testgast Hana');
 await page.locator('#clear-cart').click();
 assert.equal(await page.locator('.empty-cart').isVisible(),true);
 await page.keyboard.press('Escape');

 const booking=page.locator('#reservation-form');
 await booking.locator('[name=date]').fill('2026-09-08');
 await booking.locator('[name=guests]').selectOption('4');
 await booking.locator('[name=time]').selectOption('18:30');
 assert.equal(await booking.locator('[name=time] option[value="14:30"]').count(),0);
 assert.equal(await booking.locator('[name=time] option[value="21:15"]').count(),0);
 await booking.locator('[name=name]').fill('Testgast Reservierung');
 await booking.locator('[name=phone]').fill('+49 123456789');
 await booking.locator('[name=email]').fill('test@example.com');
 await booking.locator('[name=notes]').fill('Kinderstuhl. Testanfrage – nicht versenden.');
 await booking.locator('[type=submit]').click();
 assert.equal(await page.locator('#reservation-review').isVisible(),true);
 assert.match(await page.locator('#reservation-message').textContent(),/Personen: 4/);
 const bookingHref=await page.locator('#send-reservation').getAttribute('href');
 assert.ok(bookingHref.startsWith('https://wa.me/4915257186870?text='));
 for(const text of ['Datum: 2026-09-08','18:30 Uhr','Kinderstuhl','test@example.com'])assert.ok(decodeURIComponent(bookingHref).includes(text),text);
 await page.locator('#copy-reservation').click();
 await expect(page.locator('#reservation-copy-status')).toContainText('kopiert');
 await page.locator('#reservation-booking').screenshot({path:'test-results/reservation-review-mobile.png'});
 axe=await new AxeBuilder({page}).analyze();assert.deepEqual(axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);
 await page.locator('#edit-reservation').click();
 assert.equal(await booking.locator('[name=name]').inputValue(),'Testgast Reservierung');
 await booking.locator('[type=submit]').click();
 await page.clock.setSystemTime(new Date('2026-09-08T16:15:00Z'));
 await page.locator('#send-reservation').click();
 assert.equal(await booking.isVisible(),true);
 assert.match(await page.locator('#reservation-error').textContent(),/abgelaufen/);
 const storage=await page.evaluate(()=>JSON.stringify(localStorage));
 assert.ok(!storage.includes('Testgast'));
 assert.deepEqual(errors,[]);
 console.log('Actual flyer menu: search, variants, dietary filters, persistence, cart math, checkout, booking, stale time, clipboard and accessibility passed. No request sent.');
} finally {await browser.close();}
