import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import * as c from '../assets/js/config.js';
import { MENU } from '../assets/js/menu.js';
import { renderMenu, renderMenuNavigation, renderMenuTools } from './render-menu.mjs';
import { escapeHTML as e, money } from '../assets/js/core.js';
const [street,postalLocality,country]=c.ADDRESS.split(',').map(part=>part.trim());
const [postalCode,...cityParts]=postalLocality.split(' ');
const hourLines=period=>c.OPENING_HOURS[period].map(([start,end])=>`${e(start)} – ${e(end)} Uhr`).join('<br>');
const hours=`<div class="hours"><div><strong>Montag – Freitag</strong><span>${hourLines('weekday')}</span></div><div><strong>Samstag, Sonntag &amp; Feiertage</strong><span>${hourLines('weekend')}</span></div></div>`;
const ids=new Set();
for(const category of MENU.categories){
 if(!/^[a-z0-9-]+$/.test(category.id)) throw Error('Invalid category ID');
 for(const item of category.items){
  if(!item.id || ids.has(item.id) || !item.name || !item.number || !Number.isSafeInteger(item.priceCents) || item.priceCents<0) throw Error('Invalid or duplicate menu item');
  ids.add(item.id);
 }
}
if(MENU.categories.length && (!MENU.verified || !MENU.source)) throw Error('Menu requires source and verification');
const menuHTML=renderMenu(MENU);
const gallery=[
 {id:'04',title:'Japanische Details',alt:'Gastraum mit japanischen Holzdetails und Laternen'},
 {id:'01',title:'Bar & Empfang',alt:'Bar und Empfangsbereich im HANA Restaurant'},
 {id:'03',title:'Plätze im Tageslicht',alt:'Heller Sitzbereich mit japanischem Wandbild'},
 {id:'06',title:'Unter Kirschblüten',alt:'Sitzbereich mit Kirschblüten und HANA Wandzeichen'},
 {id:'05',title:'Am Fenster',alt:'Ruhiger Sitzbereich am Fenster im HANA'},
 {id:'02',title:'Blick zur Sushi-Theke',alt:'Gastraum mit Holztischen und Blick auf die Sushi-Theke'},
 {id:'07',title:'Grün & gemütlich',alt:'Gemütlicher Gastraum mit grüner Deckendekoration'}
].map(g=>`<button class="gallery-item" data-photo="assets/images/hana-interior-${g.id}.webp" data-caption="${e(g.alt)}" aria-label="Bild vergrößern: ${e(g.alt)}"><img src="assets/images/hana-interior-${g.id}.webp" alt="${e(g.alt)} – HANA Japanisches Restaurant Olsberg" width="1276" height="956" loading="lazy" decoding="async"><span class="gallery-item-meta" aria-hidden="true"><strong>${e(g.title)}</strong><i>↗</i></span></button>`).join('');
const schema={'@context':'https://schema.org','@type':'Restaurant','@id':c.SITE_URL+'/#restaurant',name:c.RESTAURANT_NAME,image:c.SITE_URL+'/assets/images/hana-hero-v2.webp',address:{'@type':'PostalAddress',streetAddress:street,postalCode,addressLocality:cityParts.join(' '),addressCountry:country==='Deutschland'?'DE':country},telephone:c.PHONE_NUMBER,email:c.EMAIL_ADDRESS,url:c.SITE_URL,servesCuisine:['Japanisch','Sushi','Sashimi','Asia Fusion'],menu:c.SITE_URL+'/#speisekarte',openingHoursSpecification:[...c.OPENING_HOURS.weekday.map(([opens,closes])=>({'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday'],opens,closes})),...c.OPENING_HOURS.weekend.map(([opens,closes])=>({'@type':'OpeningHoursSpecification',dayOfWeek:['Saturday','Sunday','PublicHolidays'],opens,closes}))],sameAs:[c.FACEBOOK_URL,c.INSTAGRAM_URL].filter(Boolean)};
const values={HOURS:hours,GALLERY:gallery,SCHEMA:JSON.stringify(schema).replace(/</g,'\\u003c'),PHONE:c.PHONE_NUMBER,EMAIL:c.EMAIL_ADDRESS,SITE:c.SITE_URL,MAP:c.GOOGLE_MAPS_URL,MAP_EMBED:e(c.MAP_EMBED_URL),RESERVATION:c.RESERVATION_URL||'#reservation-booking',RESERVATION_LABEL:'Tisch online reservieren',SOCIAL:[['Facebook',c.FACEBOOK_URL],['Instagram',c.INSTAGRAM_URL]].filter(([,url])=>url).map(([label,url])=>`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`).join(''),MENU:menuHTML||`<div class="menu-pending"><span class="menu-symbol" aria-hidden="true">HANA</span><div><h3>Unsere neue Speisekarte ist bald für Sie da.</h3><p>Bis dahin beraten wir Sie gerne persönlich zu unseren Gerichten und Ihrer Bestellung zur Abholung.</p><a class="text-link" href="tel:${c.PHONE_NUMBER}">Speisekarte telefonisch erfragen <span aria-hidden="true">↗</span></a></div></div>`,MENU_NAV:renderMenuNavigation(MENU),MENU_TOOLS:renderMenuTools(),PDF:c.MENU_PDF_URL?`<a class="text-link" href="${e(c.MENU_PDF_URL)}" target="_blank" rel="noopener">Speisekarte als PDF ansehen ↗</a>`:'',LEGEND:`<p class="menu-source-note">${e(MENU.sourceNotes || '')}</p>`+Object.entries({Allergene:MENU.allergens,Zusatzstoffe:MENU.additives}).filter(([,values])=>Object.keys(values).length).map(([label,values])=>`<details class="legend"><summary>${label}</summary><p>${Object.entries(values).map(([key,value])=>`${e(key)}: ${e(value)}`).join(' · ')}</p></details>`).join('')};
let html=await readFile('scripts/index.template.html','utf8');
html=html.replace('{{MENU_SECTION}}',await readFile('scripts/menu-section.template.html','utf8'));
html=html.replace('{{BOOKING}}',await readFile('scripts/reservation.template.html','utf8'));

html=html.replaceAll('Carlsauestraße 6',e(street)).replaceAll('59939 Olsberg',e(postalLocality)).replaceAll('+49 2962 9766328',e(c.PHONE_NUMBER==='+4929629766328'?'+49 2962 9766328':c.PHONE_NUMBER));
html=html.replace(/\{\{([A-Z_]+)\}\}/g,(_,key)=>{if(!(key in values)) throw Error('Unknown token '+key);return values[key];});
html=html.replace('Mo – Fr 12:00–14:30 · 17:00–22:00 Uhr', 'Mo – Fr '+c.OPENING_HOURS.weekday.map(p=>p.join('–')).join(' · ')+' Uhr').replace('Sa, So &amp; Feiertage 12:00–15:00 · 16:00–22:00 Uhr','Sa, So &amp; Feiertage '+c.OPENING_HOURS.weekend.map(p=>p.join('–')).join(' · ')+' Uhr');
await writeFile('index.html',html);
await writeFile('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${c.SITE_URL}/sitemap.xml\n`);
await writeFile('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${c.SITE_URL}/</loc></url></urlset>\n`);
const legalShell=(title,content)=>`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><title>${title} | HANA Japanisches Restaurant</title><link rel="icon" href="favicon.ico"><link rel="stylesheet" href="assets/css/style.css"><link rel="stylesheet" href="assets/css/flyer-theme.css"></head><body><header class="site-header"><div class="container header-inner"><a class="brand" href="index.html"><img class="brand-logo" src="assets/images/hana-logo-from-pdf-hd.webp" alt="" width="57" height="57"><span>HANA<span class="brand-dot">.</span></span><small>JAPANISCHES RESTAURANT</small></a><a class="text-link" href="index.html">Zurück zur Startseite →</a></div></header><main class="container legal"><h1>${title}</h1>${content}</main></body></html>`;
await writeFile('impressum.html',legalShell('Impressum',`<h2>Kontakt</h2><p>${e(c.RESTAURANT_NAME)}<br>${e(c.ADDRESS)}<br>Telefon: <a href="tel:${c.PHONE_NUMBER}">${c.PHONE_NUMBER}</a><br>E-Mail: <a href="mailto:${c.EMAIL_ADDRESS}">${c.EMAIL_ADDRESS}</a></p><h2>Betreiberangaben</h2><p>Die Angaben zum rechtlichen Betreiber werden derzeit vervollständigt. Bitte wenden Sie sich bei Fragen an den oben genannten Kontakt.</p><!-- RELEASE BLOCKER: Obtain verified proprietor/legal entity, representative, register and VAT details where applicable. Do not publish this draft as a completed legal notice. --><h2>Gestaltung</h2><p>Gestaltet von HoangCaster</p>`));
await writeFile('datenschutz.html',legalShell('Datenschutz',`<p>Diese Übersicht beschreibt die technischen Funktionen dieser Website. Die vollständigen Angaben zum Verantwortlichen und zum eingesetzten Hosting werden vor der Veröffentlichung ergänzt.</p><!-- RELEASE BLOCKER: Complete and approve privacy notice for actual legal entity and deployment provider. --><h2>Kontakt zum Restaurant</h2><p>${e(c.RESTAURANT_NAME)}<br>${e(c.ADDRESS)}<br><a href="mailto:${c.EMAIL_ADDRESS}">${c.EMAIL_ADDRESS}</a></p><h2>Warenkorb auf Ihrem Gerät</h2><p>Der Warenkorb wird im lokalen Speicher Ihres Browsers unter „hana-cart-v1“ abgelegt. Gespeichert werden die Kennungen der Gerichte und deren Anzahl. Name, Telefonnummer, E-Mail-Adresse und Bestellhinweise werden dort nicht gespeichert. Mit „Warenkorb leeren“ oder über die Browsereinstellungen können Sie die Warenkorbdaten löschen.</p><h2>Bestell- und Reservierungsanfragen</h2><p>Beim Ausfüllen des Formulars werden Ihre Angaben zunächst nur auf dieser Seite verarbeitet. Wenn Sie den WhatsApp-Link öffnen, werden Sie zu WhatsApp weitergeleitet. Die vorbereitete Nachricht wird erst übermittelt, wenn Sie sie dort absenden. Dabei verarbeitet WhatsApp Ihre Angaben nach der <a href="https://www.whatsapp.com/legal/privacy-policy-eea" target="_blank" rel="noopener noreferrer">Datenschutzrichtlinie von WhatsApp</a>. Eine Bestellung oder Reservierung ist erst nach Bestätigung durch HANA verbindlich.</p><h2>Google Maps und externe Links</h2><p>Google Maps wird beim Aufruf dieser Seite eingebunden. Dabei verbindet sich Ihr Browser mit Google; unter anderem kann Ihre IP-Adresse übermittelt werden. Auch „Route planen“ öffnet Google Maps. Informationen finden Sie in der <a href="https://policies.google.com/privacy?hl=de" target="_blank" rel="noopener noreferrer">Datenschutzerklärung von Google</a>.</p><h2>Schriftarten, Bilder und Analyse</h2><p>Schriftarten und Bilder werden mit der Website ausgeliefert. Diese Website verwendet keine Analyse- oder Werbetracker.</p><h2>Hosting und weitere Informationen</h2><p>Beim Abruf der Website verarbeitet der Hosting-Anbieter technische Verbindungsdaten. Die Angaben zum Anbieter, zu Speicherfristen, Rechtsgrundlagen und Betroffenenrechten werden für den tatsächlich eingesetzten Betrieb ergänzt. Bei Fragen wenden Sie sich bitte an den oben genannten Kontakt.</p>`));
console.log(`Built static HTML with ${ids.size} verified menu items.${!ids.size?' NEW MENU REQUIRED before launch.':''}`);
await mkdir('dist',{recursive:true});
for(const file of ['index.html','impressum.html','datenschutz.html','robots.txt','sitemap.xml','favicon.ico'])await cp(file,`dist/${file}`);
for(const folder of ['css','js','images','fonts','menu'])await cp(`assets/${folder}`,`dist/assets/${folder}`,{recursive:true});
console.log('Deployable static files: dist/');
